### ISSUE TITLE
Error patching with OneLauncher

### ISSUE THREAD

**Issue by Git-Forked** [JuneStepp/OneLauncher#56] opened 2024-07-25 02:01 UTC
```
Connecting to patch.lotro.com:6015

checking data...
Failed to check data: Unknown result code: 0x81930003

*** Finished ***
```

Running from Linux

**Comment by JuneStepp** [comment] 2024-07-25 14:13
Can't reproduce this. Could you double check to see if the issue is still happening and if this is a problem with the official launcher as well? The official launcher can be opened from the settings menu.

**Comment by Git-Forked** [comment] 2024-07-26 02:00
I ended up doing a "repair" of the game, and afterwards I did get a successful patch from OneLauncher.  
I am trying to find the cause of the issue, and it may have been something to do with Steam's update of Proton Experimental.

**Comment by JuneStepp** [comment] 2024-07-26 02:55
Closing this but feel free to add if you find out what the issue was.

**Closed by JuneStepp** 2024-07-26 02:55 UTC
